[package]
name = "thang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twilight-cache-inmemory = "0.11"
twilight-gateway = "0.11"
twilight-http = "0.11"
twilight-model = "0.11"
dotenv = "0.15"

[dependencies.futures-util]
version = "0.3"
default-features = false

[dependencies.tokio]
version = "1.18"
features = ["macros", "rt-multi-thread"]
default-features = false
