- name: eludris-owo # list of "virtual channels"
  discord: [1034208225865764944] # list of Discord channel ids (optional)
  eludris: [http://172.17.0.1:7159] # list of Eludris channel urls (optional)
  revolt: [01FNYDT71YB5ZWFQ7WYBTJXANG] # list of Revolt channel ids (optional)
