version: "3"

x-restart-policy:
  &restart_policy
  restart: unless-stopped

x-service:
  &service
  <<: *restart_policy
  depends_on: [ keydb ]
  links: [ keydb ]
  pull_policy: build
  volumes:
    - ./config.yml:/config.yml

services:
  discord:
    <<: *service
    build:
      context: .
      dockerfile: discord/Dockerfile
    environment:
      # ...oh wait
      REDIS_URL: redis://keydb:6379
      DISCORD_TOKEN: $DISCORD_TOKEN
      RUST_LOG: ${RUST_LOG:-INFO}
  eludris:
    <<: *service
    build:
      context: .
      dockerfile: eludris/Dockerfile
    environment:
      REDIS_URL: redis://keydb:6379
      RUST_LOG: ${RUST_LOG:-INFO}
  revolt:
    <<: *service
    build:
      context: .
      dockerfile: revolt/Dockerfile
    environment:
      REDIS_URL: redis://keydb:6379
      REVOLT_TOKEN: $REVOLT_TOKEN
      RUST_LOG: ${RUST_LOG:-INFO}
  keydb:
    <<: *restart_policy
    image: eqalpha/keydb
