version: "3"

x-restart-policy:
  &restart_policy
  restart: unless-stopped

services:
  discord:
    <<: *restart_policy
    build:
      context: .
      dockerfile: discord/Dockerfile
    pull_policy: build
    depends_on: [ keydb ]
    links: [ keydb ]
    env_file: .env
    environment:
      # ...oh wait
      REDIS_URL: redis://keydb:6379
  eludris:
    <<: *restart_policy
    build:
      context: .
      dockerfile: eludris/Dockerfile
    pull_policy: build
    depends_on: [ keydb ]
    links: [ keydb ]
    env_file: .env
    environment:
      REDIS_URL: redis://keydb:6379
  keydb:
    <<: *restart_policy
    image: eqalpha/keydb
